name: Deploy docs   # scelto a piacimento

on:
  push:
    branches: [ main ]   # si attiva ad ogni push sul main aggiornando quindi la docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest   # eseguito su un runner effimero con OS ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # clona il repo sul runner, e' del tipo owner/repo@version

      - name: Setup Python
        uses: actions/setup-python@v4   # installa il python, versione specificata sotto, sul runner
        with:
          python-version: "3.11"

      - name: Install MkDocs + theme   # installa mkdocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site   # converte i markdown in HTML e lo mette in site/, --strict fallisce se link non funzionano, se il .nav contiene errori o se ci sono file mancanti
        run: |
          mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3   # committo site/ sul branch gh-pages che hosta il webiste con la docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # lo inietta github
          publish_dir: ./site   # pubblica /site
